### ISSUE TITLE
Pre-process data for BIDMach

### ISSUE THREAD

**Issue by davclark** [berkeley-dsc/destress#2] opened 2015-02-04 02:12 UTC
From John:

> I suggest running the current XML tokenizers to get started. e.g. xmltweet. That produces files that BIDMach consumes directly. 
> 
> No need to do regexp parsing in the tokenizer, we'll do it later. 
> 
> The tweet tokenizer already has a regexp in it that should tokenize most emoticons.

@peparedes has run one (of many!) files through the tokenizer.

**Comment by coryschillaci** [comment] 2015-02-26 01:38
@helgammal Agreed to build a script to merge the dictionaries built after running xmltweet on subsets of the data. 

@lambdaloop Is assigned to concatenate the xml files (by folder? target size is ~100Mb) for more efficient parsing.

**Comment by coryschillaci** [comment] 2015-02-26 01:41
Closing as duplicate of the tasks in issue 3.

**Closed as completed by coryschillaci** 2015-02-26 01:41 UTC
